### ISSUE TITLE
Please share a list of the equipments in your home office

### ISSUE THREAD

**Issue by dewan-ahmed** [developit/ama#1]
Looking for suggestions on camera, light and microphone for better-quality podcast/streaming.

**Comment by developit** [comment]
Hi @dewan-ahmed!

#### My current setup

| Thing | Model Numbers | Notes
|---|---|---
Dual monitors | [LG 27UL550-W](https://amzn.to/2JFTpeu) <br> [LG 32UD59-B](https://amzn.to/39D340u) | I bought one 4K to replace the other when it died.<br>Then I ended up taking the first one apart and fixing it.
Monitor arms | two [Autonomous.ai monitor arms](https://www.autonomous.ai/office-accessories/monitor-arm?rid=2c944c)
4K aux monitor | [Lilliput A12](https://amzn.to/3lyIL6D) | for video calls + teleprompter
Camera | [Sony α6600 mirrorless](https://amzn.to/3oaeAVc)
video capture for camera | [AVerMedia Live Gamer Portable 2 Plus](https://amzn.to/36zmAc8)
Desk | [Autonomous.ai Smartdesk Home 2](https://www.autonomous.ai/standing-desks/smartdesk-2-home?rid=2c944c) | It's the cheapest and it works great.
Chair | [Autonomous.ai Kinn chair](https://www.autonomous.ai/office-chairs/kinn-chair?rid=2c944c)
Heated mouse pad / desk mat | [Olidik Warm Desk Pad Extended Edition, 31" x 13"](https://amzn.to/2I7CAce) | I really like this, but I wish my keyboard was warm too.<br>My fingers are like a dead person's fingers.
Foot rest | [Everlasting comfort office foot rest](https://amzn.to/3lsONpq)
Uninterruptible Power Supply | [CyberPower 1500VA/900W CP1500AVRLCD](https://amzn.to/3my7lWN) | My house has bad wiring and the breakers trip multiple times per day, this prevents my computers from being ruined.
Key light | [Falcon Eyes SO-48TDX](https://amzn.to/3mAofUH)
Key light stand | [Manfrotto 1004BAC Master Stand](https://amzn.to/3fYJ6hW)

#### Other stuff:

My drums are a Roland TD-30K kit (superseded by the [TD-50K](https://amzn.to/3g2JRXp)), to which I have added a 10" floor tom, two 8" rack toms, two 6" splashes and two 10" crashes. Some of the extra cymbals are routed through a Roland Octapad (SPD-30)

I've probably missed a bunch of stuff, let me know if there was something specific you were wondering about!

**Comment by dewan-ahmed** [comment]
Thanks a bunch @developit for this detailed list.

I was wondering if you could suggest a slightly more affordable option for camera+video capture for camera.

**Comment by developit** [comment]
For sure! The camera is from work, so it's more pricey than I would ever have picked myself. The capture card I actually bought because I thought it did 4K video capture, but it's only 1080p (with 4K passthru, but I don't care about passthru). 

For capturing, it turns out most video conferencing apps can't handle high resolution input anyway. I usually have to downscale mine to 720p in order to prevent my video from being squished to 4:3.  Given that, I'd probably go with [this $18 USB capture dongle from Amazon](https://amzn.to/3muuDg2) based on reviews and specs. The image quality coming from a good camera through that cheap capture device would still be way better than a webcam.

For the camera, it seems like Sony offers a much cheaper version the same camera:
[Sony a6000 mirrorless](https://amzn.to/33FP7uO)

But for the price, a 1080p camcorder like this feels like the way to go:
[Sony - Handycam CX405](https://www.bestbuy.com/site/sony-handycam-cx405-flash-memory-camcorder-black/2964179.p?skuId=2964179&ref=212&loc=1&extStoreId=1088&ref=212&loc=1&ds_rl=1268655&gclid=Cj0KCQiAk53-BRD0ARIsAJuNhpuqUxNh-9g8feyKXOU9k_MH9r4EcAQYpGCSEFCgNsePv3KJ6PbM1u4aAnlyEALw_wcB&gclsrc=aw.ds)

**Comment by dewan-ahmed** [comment]
Great! Much appreciated.

**Comment by benswinburne** [comment]
Interested to hear how you use the Lilliput A12 for video calls.

Do you simply have it plugged in as another screen and you drag whatever application is being used for the call onto that screen or do you use it more to show you what your camera can see?

**Comment by developit** [comment]
Apologies for not seeing your comment @benswinburne. I currently use it as a third monitor connected to my work mac via HDMI through a USB-C hub, which limits it to 4K@30Hz. I've been toying with the idea of driving it (and the camera) via a Raspberry Pi 4B, but I haven't done it yet because I'm a little worried ~1.8GHz and a 600mhz GPU won't be able to do the transcoding adequately. If it can though, I would certainly love to offload that monitor from the Macbook - right now I disable HDMI when I'm not on calls to try to claw back a bit of performance on this very slow machine.
