### ISSUE TITLE
How does the Prerendering work in WMR?

### ISSUE THREAD

**Issue by Krutsch** [developit/ama#11]
And are there any framework agnostic solutions for prerendering + hydrating?

**Comment by remorses** [comment]
I am also interested on why you are using web workers for the prerendering code

**Comment by developit** [comment]
Hiya! @remorses - it's using Node's `worker_threads`, mainly to separate out the application's code from WMR's code when executing everything. It's also because pages are prerendered in parallel, and it's much faster+easier to do so when each gets a seperate thread.

Regarding framework-agnosticism, WMR's approach is actually completely framework-agnostic. It scans your HTML to find the first module, imports it in Node and looks for a `prerender` export. You provide that exported function, and the API contract is pretty straightfoward:

```js
export async function prerender(data) {
  return {
    html:  '<div>the HTML you want to inject into the page</div>',
    links: [
      '/some-other-page' // any links here will get "crawled" and prerendered
    ]
  };
}
```

On the client, we shipped `preact-iso` to do hydration, but it's pretty much just standard preact hydration. Any DOM framework that supports hydrating from HTML can do the same thing, the only "special" part is that we disable hydration during development because prerendering is disabled there too:

```js
// "preact-iso/hydrate"
import { hydrate, render } from 'preact';
export default rootComponent => {
  // Pre-rendered pages have a `<script type="isodata">`, which means we should hydrate:
  if (document.querySelector('script[type=isodata]')) {
    hydrate(rootComponent, document.body);
  } else {
    render(rootComponent, document.body);
  }
};
```

I think some folks are already looking at building WMR adapters for Svelte, which would make a nice example of how to use WMR for non-Preact apps. We only put `preact-iso` together to provide "built-in" hydration and prerendering support the week before WMR was released, prior to that it was just a couple functions copied between projects.
